version: '3.8'
services:
    app: # サービス名。appじゃなくてもいい
        build: ./infra/php  # docker buildを実行する際の現在の作業ディレクトリ
        volumes:
            - ./backend:/work

    web:
        image: nginx:1.18-alpine    # nginxは1.10, 1.12 等の偶数のバージョンが安定バージョン
        ports:
            - 10080:80  # nginxへ外(ホスト側)からコンテナ内へアクセスさせるため公開用のポートを設定
        volumes:    # ホスト側にあるディレクトリ、ファイルをコンテナ内へマウント
            - ./backend:/work
            - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /work

    db:
        image: mysql:8.0
        volumes:
            - db-store:/var/lib/mysql
            - ./infra/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            - MYSQL_DATABASE=laravel_local
            - MYSQL_USER=phper
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
            - TZ=Asia/Tokyo

volumes:
    db-store:
